name: Rebuild ics

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'  # 设置定时任务每小时执行一次

jobs:
  rebuild_shuyz_website:
    runs-on: ubuntu-latest
    steps:
      - name: Execute ics
        run: |
          python main.py
           
