# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ "major" ]
#  push:
#    branches:
#      - master
  schedule:
    - cron: '0 * * * *'  # 设置定时任务每小时执行一次

#jobs:
#  trigger:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Trigger another workflow via repository_dispatch
#      run: |
#        curl -X POST -H "Accept: application/vnd.github.v3+json" \
#            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
#            https://api.github.com/repos/nxy1999/cs-calendar/dispatches \
#            -d '{"event_type": "major"}'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Commit and push changes
        run: |
          git config --local user.email "2924157356@qq.com"
          git config --local user.name "nxy"  # git pull
          git add matches_calendar.ics  # git commit -m "Update match data" || echo "No changes to commit"   git push origin master # Push changes  echo "Changes pushed to GitHub repository"

          git diff --staged --quiet && echo "No changes to commit" || (git commit -m "Update match data" && git push origin master && echo "Changes pushed to GitHub repository")
        env:
          github_token: ${{ secrets.ACCESS_TOKEN }}

